# 连接池通用配置
initialSize: 5
minIdle: 5
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000

server:
  port: 9999

spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      maxActive: 8 # 连接池最大连接数（使用负值表示没有限制）
      maxWait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxIdle: 8 # 连接池中的最大空闲连接
      minIdle: 0 # 连接池中的最小空闲连接
      timeout: 5000 # 连接超时时间（毫秒）
  # main: 
    # allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    other:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/ds1
     username: root
     password: 123456
     test-on-borrow: false
     test-while-idle: true
     time-between-eviction-runs-millis: 18800
     filters: mergeStat,wall,slf4j
     connectionProperties: druid.stat.slowSqlMillis=2000
     validationQuery: SELECT 1
     poolPreparedStatements: true
    sharding:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0
        username: root
        password: 123456
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
        filters: mergeStat,wall,slf4j
        connectionProperties: druid.stat.slowSqlMillis=2000
        validationQuery: SELECT 1
        poolPreparedStatements: true
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1
        username: root
        password: 123456
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
        filters: mergeStat,wall,slf4j
        connectionProperties: druid.stat.slowSqlMillis=2000
        validationQuery: SELECT 1
        poolPreparedStatements: true

mybatis:
  mapperLocations:
    classpath:mapper/*.xml
    
