# 连接池通用配置
initialSize: 5
minIdle: 5
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000

server:
  port: 9999

spring:
    # main:
    # allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    other:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ds1
      username: root
      password: 123456
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      filters: mergeStat,wall,slf4j
      connectionProperties: druid.stat.slowSqlMillis=2000
      validationQuery: SELECT 1
      poolPreparedStatements: true
    sharding:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0
        username: root
        password: 123456
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1
        username: root
        password: 123456

mybatis:
  mapperLocations:
    classpath:mapper/*.xml

